export {
  PROTOCOL_VERSION,
  RUNTIME_PROTOCOL_VERSION,
  CAPABILITY_PROFILE,
  SCHEMA_VERSION,
  DATA_CATEGORIES,
  TERMINAL_OUTCOMES,
  RUN_STOP_REASONS,
  CAPABILITY_RESULT_STATUSES,
  ATTENTION_REQUIRED_CAUSES,
  WAIT_END_REASONS,
  WAIT_CONDITIONS,
  TASK_MODES,
  TASK_LIFECYCLES,
  ACTION_RISKS,
  TARGET_ROLES,
  TARGET_MINT_POLICIES,
  AGENT_UPLOAD_MAX_FILES,
  AGENT_UPLOAD_MAX_BASE64_CHARS,
  GRANT_LIFETIMES,
  SESSION_STORAGE_ALLOWLIST,
  OPERATION_MARKER_FIELDS,
  FORM_VALUE_DENIED_REPRESENTATIONS,
  FORM_VALUE_WITHHELD_CLASSES,
  LOG_FORBIDDEN_FIELDS,
  ERROR_CODES,
  TARGET_KINDS,
  TARGET_VISIBILITIES,
  REASON_CODE_PATTERN,
  REASON_CODE_MAX_CHARS,
} from "./common.js";
export type {
  ActionRisk,
  DataCategory,
  TaskLifecycle,
  TargetRole,
  TargetMintPolicy,
  TerminalOutcome,
  RunStopReason,
  CapabilityResultStatus,
  AttentionRequiredCause,
  WaitEndReason,
  WaitCondition,
  TargetVisibility,
  TargetKindValue } from "./common.js";
export { BRIDGE_ACTIONS, RUNTIME_ACTIONS, PAGE_READ_DATA_CATEGORIES } from "./capabilities.js";
export type { RuntimeAction } from "./capabilities.js";
export { createBounds, DEFAULT_BOUNDS, TRUNCATION_DIMENSIONS } from "./bounds.js";
export type { ProtocolBounds, TruncationDimension } from "./bounds.js";
export { executeActionPayloadSchema } from "./action-arguments.js";
export {
  contentRuntimeMessageSchema,
  contentResolutionReplySchema,
  contentEvaluateConditionReplySchema,
} from "./extension-runtime.js";
export type {
  ContentRuntimeMessage,
  ContentResolutionReply,
  ContentEvaluateConditionReply,
} from "./extension-runtime.js";
export { CONTENT_EXECUTION_REFUSAL_REASONS, isContentExecutionRefusalReason } from "./extension-runtime.js";
export type { ContentExecutionRefusalReason } from "./extension-runtime.js";
export { KEY_PRESS_KEYS, KEY_PRESS_MODIFIERS } from "./action-arguments.js";
export type { KeyPressKey } from "./action-arguments.js";
export {
  AGENT_TOOL_OUTCOMES,
  AGENT_TOOL_NAMES,
  AGENT_EFFECT_TOOL_NAMES,
  AGENT_TOOL_DESCRIPTORS,
  AGENT_BATCH_STEP_TOOL_NAMES,
  AGENT_CALL_TIMEOUT_MS,
  AGENT_CALL_TIMEOUT_SLACK_MS,
  AGENT_MAX_CALL_TIMEOUT_MS,
  AGENT_EXPORT_CALL_TIMEOUT_MS,
  agentCallBoundMs,
  isAgentEffectTool,
  SITE_MODES,
  agentToolOutcomeSchema,
  agentToolNameSchema,
  agentToolArgSchemas,
  agentNativeRequestSchema,
  agentNativeResponseSchema,
  agentControlFrameSchema,
  AGENT_LINK_PROTOCOL,
  agentLinkFrameSchema,
  AGENT_PROMPT_KINDS,
  ATTENTION_SENTENCES,
  // 014: the owner's own vocabulary - what a stop or an interrupt says, the reasons the
  // three consent surfaces answer with, the two sentences an interrupted call may carry, and
  // the shape of a path on the owner's machine.
  AGENT_STOP_REASONS,
  AGENT_CONSENT_REASONS,
  // 015: the reasons this feature adds, each pinned to the outcome it answers with.
  AGENT_015_REASON_OUTCOMES,
  INTERRUPT_HINTS,
  UPLOAD_HINTS,
  // 003 FR-032a: a decline answers one request, an unpair the session; how each is marked and said.
  PAIRING_DECLINED_MARKER,
  PAIRING_REFUSAL_HINTS,
  // 017: the session site plan - the covered tools, the worker feature, the unavailable answer,
  // the tool's bounds and the one origin rule every party checks.
  AGENT_SITE_PLAN_COVERED_TOOLS,
  SITE_PLAN_FEATURE,
  SITE_PLAN_UNAVAILABLE,
  AGENT_SITE_PLAN_MAX_ORIGINS,
  AGENT_SITE_PLAN_MAX_PURPOSE_CHARS,
  AGENT_SITE_PLAN_MAX_STEPS,
  AGENT_SITE_PLAN_MAX_STEP_CHARS,
  sitePlanOriginProblem,
  sitePlanOriginSchema,
  agentProposeSitesArgsSchema,
  isRootDirectory,
  transitionNoticeText,
  absolutePathSchema,
  promptWaitingFrameSchema,
  agentBridgeRecordSchema,
  agentBridgeOwnerSchema,
  agentRefusalSchema,
  AGENT_COMPUTER_ACTIONS,
  AGENT_READ_PAGE_DEFAULT_DEPTH,
  AGENT_READ_PAGE_MAX_DEPTH,
  AGENT_READ_PAGE_MAX_NODES,
  AGENT_READ_PAGE_MAX_CHARS,
  agentTabsClaimResultSchema,
  agentTabsReleaseResultSchema,
  AGENT_EFFECT_VERDICTS,
  AGENT_CONSOLE_LEVELS,
  agentUploadResultSchema,
  // 013: the agent's request, the worker's arguments and the page's answer for `upload_image`.
  agentUploadImageRequestSchema,
  agentUploadImageArgsSchema,
  agentUploadImageResultSchema,
  AGENT_DIAGNOSTICS_MAX_LIMIT,
  AGENT_EVALUATE_MAX_CHARS,
  agentConsoleResultSchema,
  agentNetworkResultSchema,
  agentEvaluateResultSchema,
  agentEffectObservationSchema,
  agentEffectResultSchema,
  agentFindResultSchema,
  agentPageTextResultSchema,
  agentReadPageResultSchema,
  agentScreenshotResultSchema,
  agentTabViewSchema,
  agentTabsCreateResultSchema,
  agentTabsCloseResultSchema,
  agentNavigateResultSchema,
  agentResizeWindowResultSchema,
  AGENT_VIEWPORT_MIN_PX,
  AGENT_VIEWPORT_MAX_PX,
  agentViewportResultSchema,
  agentBatchStepSchema,
  agentBatchStepResultSchema,
  agentBatchResultSchema,
  agentWaitResultSchema,
  AGENT_WAIT_CONDITIONS,
  AGENT_DOWNLOAD_STATES,
  AGENT_DOWNLOAD_TERMINAL_STATES,
  AGENT_DOWNLOAD_ATTRIBUTIONS,
  AGENT_DOWNLOADS_KEPT,
  agentDownloadRecordSchema,
  agentDownloadsContextResultSchema,
  AGENT_RECORDING_MAX_FRAMES,
  AGENT_RECORDING_FILENAME_PATTERN,
  currentDialogSchema,
  recordingStateSchema,
  gifRecorderStatusResultSchema,
  gifRecorderExportResultSchema,
  dialogResultSchema,
  siteModeSchema,
  siteOriginSchema,
  siteModeRecordSchema,
  AGENT_PANEL_PORT_NAME,
  AGENT_BRIDGE_STATUSES,
  AGENT_SESSION_STATES,
  AGENT_SESSION_COLOURS,
  AGENT_ACTIVITY_KEPT,
  agentActivityItemSchema,
  agentBridgeStatusSchema,
  agentEffectPromptSchema,
  agentPanelStateSchema,
  agentPanelMessageSchema,
  agentPanelCommandSchema,
} from "./agent-tools.js";
export type {
  AgentToolOutcome,
  AgentToolName,
  AgentEffectToolName,
  AgentToolDescriptor,
  AgentNativeRequest,
  AgentNativeResponse,
  AgentControlFrame,
  AgentLinkFrame,
  AgentPromptKind,
  AgentStopReason,
  AgentConsentReason,
  Agent015Reason,
  PromptWaitingFrame,
  AgentBridgeRecord,
  AgentBridgeOwner,
  AgentRefusal,
  AgentComputerAction,
  AgentConsoleResult,
  AgentUploadResult,
  AgentUploadImageRequest,
  AgentUploadImageResult,
  AgentNetworkResult,
  AgentEvaluateResult,
  AgentEffectObservation,
  AgentEffectVerdict,
  AgentEffectResult,
  AgentEffectPrompt,
  AgentFindResult,
  AgentPageTextResult,
  AgentReadPageResult,
  AgentScreenshotResult,
  AgentViewportResult,
  AgentTabView,
  AgentBatchStepToolName,
  AgentBatchStep,
  AgentBatchStepResult,
  AgentBatchResult,
  AgentWaitResult,
  AgentWaitCondition,
  AgentWaitDownload,
  AgentDownloadState,
  AgentDownloadAttribution,
  AgentDownloadRecord,
  AgentDownloadsContextResult,
  AgentNavigateDownload,
  CurrentDialog,
  RecordingState,
  GifRecorderStatusResult,
  GifRecorderExportResult,
  DialogResult,
  AgentPlanPrompt,
  AgentSitePlanPrompt,
  AgentSitePlanCoveredToolName,
  AgentProposeSitesArgs,
  SiteMode,
  SiteModeRecord,
  AgentBridgeStatusValue,
  AgentBridgeDiagnostics,
  AgentSessionState,
  AgentSessionColour,
  AgentActivityItem,
  AgentNotice,
  AgentPanelState,
  AgentPanelTab,
  AgentPanelMessage,
  AgentPanelCommand,
} from "./agent-tools.js";
